[
    {
        "service": "auth-service",
        "status": "unreachable",
        "error": "HTTPConnectionPool(host='auth.example.com', port=80): Max retries exceeded with url: /health (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000002A76CBD3770>: Failed to resolve 'auth.example.com' ([Errno 11001] getaddrinfo failed)\"))"
    },
    {
        "service": "user-service",
        "status": "unreachable",
        "error": "HTTPConnectionPool(host='user.example.com', port=80): Max retries exceeded with url: /health (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000002A76CBEB890>: Failed to resolve 'user.example.com' ([Errno 11001] getaddrinfo failed)\"))"
    },
    {
        "service": "payment-service",
        "status": "unreachable",
        "error": "HTTPConnectionPool(host='payment.example.com', port=80): Max retries exceeded with url: /health (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000002A76CCD0410>: Failed to resolve 'payment.example.com' ([Errno 11001] getaddrinfo failed)\"))"
    }
]